### ISSUE TITLE
Load optimisation

### ISSUE THREAD

**Issue by BadIdeasBureau** [laquasicinque/monaco-macro-editor#1]
Looking through my worlds, I noticed that three of the five largest files on initial world load are from this module (6640.module.js 3808.module.js,, both above 750kB transferred data, and ts.worker.js, 1.3MB of transferred data, with the only larger file being the scene background and the next largest being foundry.js itself).  While caching will eliminate the impact of this after the first load, it may be worth investigating whether more of the code could be loaded as-needed, rather than on initialisation, or even on a later hook such as canvasReady where the main game assets have already loaded.

**Comment by laquasicinque** [comment]
This will be in 0.0.8
