### ISSUE TITLE
Macro editor does not obey routePrefix

### ISSUE THREAD

**Issue by elena-v2** [laquasicinque/monaco-macro-editor#2]
routePrefix is an option that indicates that Foundry is located at something other than http://example.domain/, such as 'vtt' for http://example.domain/vtt - fairly common if you're going to proxy it through a web server.

Currently, it completely ignores routePrefix so it only attempts to GET files without using it, such as 'http://example.domain/modules/monaco-macro-editor/dist/6640.module.js' rather than the correct 'http://example.domain/vtt/modules/monaco-macro-editor/dist/6640.module.js' This will almost certainly fail, and result in the module being unusable in these configuration scenarios.

**Comment by laquasicinque** [comment]
I've changed the webpack config for v0.0.8 so that it should be relative, although I've not been able to test it personally, could you let me know if it's worked @elena-v2

**Comment by elena-v2** [comment]
Just tested it on my foundry instance and it seems like everything's in order so far, I'll make an issue or bump this if something comes up in my testing. Thanks!
